'use strict';

const DEFAULT_PORT = 8787;
const DEFAULT_VERSION = '3.0.1';
const DEFAULT_START_TIMEOUT_MS = 15000;
const MAX_CONFIG_BYTES = 16 * 1024 * 1024;
const MAX_HOST_CONTEXT_CHARS = 200000;

module.exports = {
  DEFAULT_PORT,
  DEFAULT_START_TIMEOUT_MS,
  DEFAULT_VERSION,
  MAX_CONFIG_BYTES,
  MAX_HOST_CONTEXT_CHARS
};
