const fs = require('node:fs');

function replaceExact(file, before, after, expected = 1) {
  const source = fs.readFileSync(file, 'utf8');
  const count = source.split(before).length - 1;
  if (count !== expected) throw new Error('Expected ' + expected + ' anchors in ' + file + ', found ' + count);
  fs.writeFileSync(file, source.split(before).join(after), 'utf8');
}

replaceExact("vscode-host/ngrok-agent-api.js", "function upstreamMatchesPort(value, port) {\n  const target = Number(port);\n  if (!Number.isInteger(target) || target <= 0) return false;\n  const raw = String(value || '').trim();\n  if (!raw) return false;\n  if (/^\\d+$/.test(raw)) return Number(raw) === target;\n  try {\n    const parsed = new URL(raw.includes('://') ? raw : `http://${raw}`);\n    const parsedPort = Number(parsed.port || (parsed.protocol === 'https:' ? 443 : 80));\n    return parsedPort === target;\n  } catch {\n    return Number(raw.match(/:(\\d+)(?:\\/)?$/)?.[1]) === target;\n  }\n}\n", "function loopbackUpstreamHost(hostname) {\n  const value = String(hostname || '').replace(/^\\[|\\]$/g, '').toLowerCase();\n  if (value === 'localhost' || value === '::1') return true;\n  if (!/^127(?:\\.\\d{1,3}){3}$/.test(value)) return false;\n  const octets = value.split('.').map(Number);\n  return octets.length === 4 && octets.every(part => Number.isInteger(part) && part >= 0 && part <= 255);\n}\n\nfunction upstreamMatchesPort(value, port) {\n  const target = Number(port);\n  if (!Number.isInteger(target) || target <= 0) return false;\n  const raw = String(value || '').trim();\n  if (!raw) return false;\n  if (/^\\d+$/.test(raw)) return Number(raw) === target;\n  try {\n    const parsed = new URL(raw.includes('://') ? raw : `http://${raw}`);\n    if (parsed.protocol !== 'http:' || !loopbackUpstreamHost(parsed.hostname)) return false;\n    return Number(parsed.port || 80) === target;\n  } catch {\n    return false;\n  }\n}\n", 1);
replaceExact("vscode-host/ngrok-agent-api.js", "  discoverNgrokPublicUrl,\n  loopbackAgentApiBase,\n  ngrokWebAddrFromConfig,\n", "  discoverNgrokPublicUrl,\n  loopbackAgentApiBase,\n  loopbackUpstreamHost,\n  ngrokWebAddrFromConfig,\n", 1);
replaceExact("vscode-host/tunnel-controller.js", "    this.childReady = false;\n    this.borrowedProvider = false;\n    this.port = 0;\n", "    this.childReady = false;\n    this.borrowedProvider = false;\n    this.borrowedAgentApiBase = '';\n    this.borrowedPublicUrl = '';\n    this.borrowedFailureCount = 0;\n    this.port = 0;\n", 1);
replaceExact("vscode-host/tunnel-controller.js", "    this.childReady = false;\n    this.borrowedProvider = false;\n    this.ownershipFailureCount = 0;\n", "    this.childReady = false;\n    this.borrowedProvider = false;\n    this.borrowedAgentApiBase = '';\n    this.borrowedPublicUrl = '';\n    this.borrowedFailureCount = 0;\n    this.ownershipFailureCount = 0;\n", 1);
replaceExact("vscode-host/tunnel-controller.js", "      if (record && record.ownerId === ownerId) {\n        this.ownershipFailureCount = 0;\n        this.store.write(ownerId, { childPid: this.child?.pid || null });\n        return { healthy: true };\n      }\n", "      if (record && record.ownerId === ownerId) {\n        if (this.borrowedProvider) {\n          const liveUrl = await discoverNgrokPublicUrl(record.port, {\n            apiBase: this.borrowedAgentApiBase,\n            request: this.httpRequest,\n            timeoutMs: 750,\n            expectedUrl: this.borrowedPublicUrl || record.publicUrl\n          });\n          if (!liveUrl) {\n            this.borrowedFailureCount += 1;\n            if (this.borrowedFailureCount < 2) {\n              this.store.write(ownerId, { childPid: null });\n              return { healthy: false, pending: true, providerMissing: true };\n            }\n            this.logger('Existing local ngrok endpoint disappeared; releasing the borrowed tunnel attachment for recovery.');\n            this.resetOwnership(ownerId);\n            return { healthy: false, providerMissing: true, released: true };\n          }\n          this.borrowedFailureCount = 0;\n        }\n        this.ownershipFailureCount = 0;\n        this.store.write(ownerId, { childPid: this.child?.pid || null });\n        return { healthy: true };\n      }\n", 1);
replaceExact("vscode-host/tunnel-controller.js", "  adoptExistingNgrok(match, ownerId, publicUrl) {\n    const url = normalizePublicUrl(publicUrl);\n    this.ownerId = ownerId;\n    this.port = match.port;\n    this.child = null;\n    this.childReady = false;\n    this.borrowedProvider = true;\n    this.store.write(ownerId, {\n", "  adoptExistingNgrok(match, ownerId, publicUrl, agentApiBase = '') {\n    const url = normalizePublicUrl(publicUrl);\n    this.ownerId = ownerId;\n    this.port = match.port;\n    this.child = null;\n    this.childReady = false;\n    this.borrowedProvider = true;\n    this.borrowedAgentApiBase = String(agentApiBase || '');\n    this.borrowedPublicUrl = url;\n    this.borrowedFailureCount = 0;\n    this.store.write(ownerId, {\n", 1);
replaceExact("vscode-host/tunnel-controller.js", "return this.adoptExistingNgrok(match, ownerId, reusableUrl);", "return this.adoptExistingNgrok(match, ownerId, reusableUrl, launch.agentApiBase);", 2);
replaceExact("extension.js", "  if(editor){\n    const rel = relToRoot(editor.document.uri.fsPath);\n", "  if(editor && editor.document.uri.scheme !== 'output'){\n    const rel = relToRoot(editor.document.uri.fsPath);\n", 1);
replaceExact("extension.js", "  const visibleEditors = vscode.window.visibleTextEditors.map(e=>({\n    path: relToRoot(e.document.uri.fsPath) || e.document.uri.toString(),\n    languageId: e.document.languageId,\n    isDirty: e.document.isDirty,\n    selection: rangePublic(e.selection)\n  })).slice(0,20);\n", "  const visibleEditors = vscode.window.visibleTextEditors\n    .filter(e=>e.document.uri.scheme !== 'output')\n    .map(e=>({\n      path: relToRoot(e.document.uri.fsPath) || e.document.uri.toString(),\n      languageId: e.document.languageId,\n      isDirty: e.document.isDirty,\n      selection: rangePublic(e.selection)\n    })).slice(0,20);\n", 1);
replaceExact("tests/ngrok-agent-api.test.cjs", "  assert.equal(upstreamMatchesPort('8787', 8787), true);\n  assert.equal(upstreamMatchesPort('localhost:8787', 8787), true);\n});\n", "  assert.equal(upstreamMatchesPort('8787', 8787), true);\n  assert.equal(upstreamMatchesPort('localhost:8787', 8787), true);\n  assert.equal(upstreamMatchesPort('http://127.0.0.2:8787', 8787), true);\n  assert.equal(upstreamMatchesPort('http://[::1]:8787', 8787), true);\n  assert.equal(upstreamMatchesPort('http://192.168.1.20:8787', 8787), false);\n  assert.equal(upstreamMatchesPort('https://localhost:8787', 8787), false);\n});\n", 1);

{
  const file = 'tests/ngrok-existing-endpoint-reuse.test.cjs';
  const source = fs.readFileSync(file, 'utf8');
  const marker = "test('does not reuse a same-port endpoint whose upstream is not loopback'";
  if (!source.includes(marker)) fs.writeFileSync(file, source + "\n\ntest('does not reuse a same-port endpoint whose upstream is not loopback', async () => {\n  const stateDirectory = fs.mkdtempSync(path.join(os.tmpdir(), 'devmate-ngrok-reuse-remote-'));\n  let spawns = 0;\n  const controller = new TunnelController({\n    stateDirectory,\n    settings,\n    childProcess: fakeChildProcess(() => { spawns += 1; }),\n    httpRequest: fakeRequest({ endpoints: [{ name: 'remote', url: 'https://other.ngrok.app', upstream: { url: 'http://192.168.1.20:8788' } }] })\n  });\n  try {\n    await assert.rejects(() => controller.start(8788), /unexpected provider spawn/);\n    assert.equal(spawns, 1);\n  } finally {\n    await controller.dispose({ stopOwned: true }).catch(() => {});\n    fs.rmSync(stateDirectory, { recursive: true, force: true });\n  }\n});\n\ntest('borrowed endpoint liveness loss releases the shared record for attachment recovery', async () => {\n  const stateDirectory = fs.mkdtempSync(path.join(os.tmpdir(), 'devmate-ngrok-reuse-liveness-'));\n  let endpoints = [{ name: 'existing', url: 'https://ready.ngrok.app', upstream: { url: 'http://127.0.0.1:8788' } }];\n  const controller = new TunnelController({\n    stateDirectory,\n    settings,\n    childProcess: fakeChildProcess(() => { throw new Error('unexpected provider spawn'); }),\n    httpRequest: (_url, _options, callback) => {\n      const request = new EventEmitter();\n      request.setTimeout = () => {};\n      request.destroy = () => {};\n      request.end = () => {\n        const response = new EventEmitter();\n        response.statusCode = 200;\n        response.destroy = () => {};\n        callback(response);\n        queueMicrotask(() => {\n          response.emit('data', Buffer.from(JSON.stringify({ endpoints })));\n          response.emit('end');\n        });\n      };\n      return request;\n    }\n  });\n  try {\n    const started = await controller.start(8788);\n    assert.equal(started.attached, true);\n    endpoints = [];\n    const first = await controller.verifyOwnership();\n    assert.equal(first.pending, true);\n    assert.equal(controller.status(8788).running, true);\n    const second = await controller.verifyOwnership();\n    assert.equal(second.released, true);\n    assert.equal(controller.status(8788).running, false);\n  } finally {\n    await controller.dispose({ stopOwned: true }).catch(() => {});\n    fs.rmSync(stateDirectory, { recursive: true, force: true });\n  }\n});\n", 'utf8');
}

fs.writeFileSync("tests/vscode-context-output-filter.test.cjs", "'use strict';\n\nconst assert = require('node:assert/strict');\nconst fs = require('node:fs');\nconst path = require('node:path');\nconst test = require('node:test');\n\ntest('VS Code context capture excludes its own Output documents', () => {\n  const source = fs.readFileSync(path.resolve(__dirname, '..', 'extension.js'), 'utf8');\n  const start = source.indexOf('function collectVsCodeContext()');\n  const end = source.indexOf('function redactUrl', start);\n  assert.ok(start >= 0 && end > start);\n  const block = source.slice(start, end);\n  assert.match(block, /editor\\.document\\.uri\\.scheme !== 'output'/);\n  assert.match(block, /filter\\(e=>e\\.document\\.uri\\.scheme !== 'output'\\)/);\n});\n", 'utf8');

{
  const file = 'CHANGELOG.md';
  const source = fs.readFileSync(file, 'utf8');
  if (!source.includes('## 3.3.4')) fs.writeFileSync(file, source.replace('# Changelog\n\n', '# Changelog\n\n' + "## 3.3.4\n\n- Restricted existing-ngrok reuse to loopback HTTP upstreams on the exact DevMate Gateway port, so an unrelated same-port endpoint on another host can never be adopted.\n- Added liveness checks for borrowed local ngrok endpoints; two consecutive misses release the shared record so the existing attachment-recovery path can safely reacquire or restart the tunnel.\n- Excluded VS Code Output pseudo-documents from captured editor context to prevent provider/runtime logs from generating useless context churn.\n\n"), 'utf8');
}
